# Rust formatting configuration for threatflux-cache
# Based on the project's conventions and best practices

# Basic configuration
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true

# Code style
newline_style = "Unix"
remove_nested_parens = true
use_small_heuristics = "Default"

# Functions
fn_single_line = false
where_single_line = false

# Structs and enums
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0

# Strings
format_strings = false

# Comments
comment_width = 80
wrap_comments = false

# Trailing
trailing_comma = "Vertical"
trailing_semicolon = true

# Macros
format_macro_matchers = true
format_macro_bodies = true

# Misc
version = "Two"