# cargo-deny configuration for ThreatFlux Threat Detection
# This file controls dependency license and security checking

[advisories]
ignore = [
    "RUSTSEC-2023-0071", # RSA timing attack - in yara-x dependency
    "RUSTSEC-2024-0006", # shlex issues - in clamav build dependency
    "RUSTSEC-2025-0046", # wasmtime issue - in yara-x dependency
    "RUSTSEC-2021-0139", # ansi_term unmaintained - transitive dep
    "RUSTSEC-2024-0375", # atty unmaintained - transitive dep
    "RUSTSEC-2024-0436", # paste unmaintained - transitive dep
    "RUSTSEC-2021-0145", # atty unsound - transitive dep
    "RUSTSEC-2022-0008", # windows unsound - transitive dep
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "CC0-1.0",
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
deny = [
    { name = "openssl", version = "<0.10.45" },
    { name = "openssl-sys", version = "<0.9.75" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []